language: php

sudo: false

env:
  global:
    - COMPOSER_NO_INTERACTION="1"

php:
  - '7.0'
  - '7.1'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y p7zip
  - cd app/Resources && p7zip -d sqlite-31.db.7z

install:
  - composer install
