imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    secret: '%secret%'
    templating:
        engines: ['twig']

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        code_type: null

paysera_code_generator:
    vendor_prefix: '%vendor_prefix%'

paysera_word_net:
    sqlite_file: '%kernel.root_dir%/Resources/word_net_sqlite-31.db'
